### ISSUE TITLE
compile errors in carambola2 2.7 when selecting socat

### ISSUE THREAD

**Issue by Gittomcat** [8devices/carambola2-new-packages#2]
when selecting the Package socat in menuconfig the compile run stops with errors.

also trying to select the package socat on the target via opkg is not possible because of the pakcage being not available in the packages list.

Is there a means to install socat on Carambola2?

**Comment by mantas-p** [comment]
Hello,

socat package is broken in carambola2 branch, so it was not built for the repository. It seems upstream OpenWRT already fixed it. Until carambola2 branch is updated, I recommend to manually install from upstream:
```
cd /tmp
wget http://downloads.openwrt.org/chaos_calmer/15.05-rc3/ar71xx/generic/packages/packages/socat_1.7.3.0-1_ar71xx.ipk
opkg install socat_1.7.3.0-1_ar71xx.ipk
```

**Comment by Gittomcat** [comment]
Thanks a lot!
following your advice, socat is working properly on my carambola2 :-)
